flyway.url=jdbc:postgresql://postgres:5432/automana
flyway.user=automana_admin
flyway.locations=filesystem:/flyway/migrations/core,filesystem:/flyway/migrations/pipeline
flyway.baselineOnMigrate=false
flyway.validateOnMigrate=true
flyway.outOfOrder=false
