name: Task
description: Standard development task or action item
title: "[Task]: "
labels: ["type:task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
      placeholder: "Implement DB migration for pricing history storage."
    validations:
      required: true

  - type: select
    id: milestone
    attributes:
      label: Milestone
      description: Which milestone does this task belong to?
      options:
        - M1 - Card Catalogue
        - M2 - Core Backend
        - M3 - Pricing
        - M4 - eBay Integration
        - M5 - Automation & AI
        - M6 - Frontend

  - type: textarea
    id: subtasks
    attributes:
      label: Subtasks
      description: Checklist of work units
      placeholder: |
        - [ ] Create schema
        - [ ] Write migration script
        - [ ] Add unit tests

  - type: input
    id: estimate
    attributes:
      label: Time / Effort Estimate
      placeholder: "S / M / L or hours"

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What must be true for this task to be considered done?
      placeholder: |
        - All migrations run without errors
        - Tests pass
        - PR reviewed and merged
