// src/frontend/src/features/ebay/mockEbayApp.ts
// TODO: replace with useQuery/useMutation when /api/ebay/credentials is wired

// ── Types ─────────────────────────────────────────────────────────────────

export interface EbayCredentials {
  appId: string       // Client ID
  certId: string      // Client Secret
  devId: string
  ruName: string      // Redirect URI (RuName) — read-only, generated by backend
}

export interface OAuthScope {
  id: string
  name: string
  description: string
  required: boolean
  enabled: boolean
}

export interface ConnectionStatus {
  connected: boolean
  environment: 'sandbox' | 'production'
  lastVerified: string | null
  tokenExpires: string | null
  dailyQuota: number
  usedToday: number
}

export type SetupStep = 0 | 1 | 2 | 3

// ── Mock data ──────────────────────────────────────────────────────────────

export const MOCK_REDIRECT_URI =
  'https://auth.automana.app/oauth/callback/ebay'

export const MOCK_OAUTH_SCOPES: OAuthScope[] = [
  {
    id: 'sell.inventory',
    name: 'sell.inventory',
    description: 'Read and manage your eBay inventory listings',
    required: true,
    enabled: true,
  },
  {
    id: 'sell.account',
    name: 'sell.account',
    description: 'Access your eBay seller account settings',
    required: true,
    enabled: true,
  },
  {
    id: 'sell.marketing',
    name: 'sell.marketing',
    description: 'Create and manage eBay marketing promotions',
    required: false,
    enabled: false,
  },
  {
    id: 'sell.fulfillment',
    name: 'sell.fulfillment',
    description: 'Manage order fulfillment and shipping details',
    required: true,
    enabled: true,
  },
  {
    id: 'buy.browse',
    name: 'buy.browse',
    description: 'Search and browse eBay item catalog for pricing',
    required: true,
    enabled: true,
  },
  {
    id: 'commerce.identity',
    name: 'commerce.identity',
    description: 'Access verified identity for user authorization',
    required: true,
    enabled: true,
  },
]

export const MOCK_CONNECTION_STATUS: ConnectionStatus = {
  connected: false,
  environment: 'production',
  lastVerified: null,
  tokenExpires: null,
  dailyQuota: 5000,
  usedToday: 0,
}

export const MOCK_CONNECTED_STATUS: ConnectionStatus = {
  connected: true,
  environment: 'production',
  lastVerified: '2026-05-06T10:32:00Z',
  tokenExpires: '2026-06-06T10:32:00Z',
  dailyQuota: 5000,
  usedToday: 247,
}

export const SETUP_STEPS = [
  { label: 'Create app' },
  { label: 'Paste keys' },
  { label: 'OAuth scopes' },
  { label: 'Verify' },
]

// ── Help links ─────────────────────────────────────────────────────────────

export const HELP_LINKS = [
  { label: 'eBay Developer Portal', href: 'https://developer.ebay.com' },
  { label: 'Create an application', href: 'https://developer.ebay.com/my/keys' },
  { label: 'Configure RuName', href: 'https://developer.ebay.com/my/auth' },
  { label: 'OAuth scope reference', href: 'https://developer.ebay.com/api-docs/static/oauth-scopes.html' },
]

export const BYOA_BENEFITS = [
  'Your API quota is never shared with other AutoMana users',
  'Credentials stay in your eBay account — we only store tokens',
  'Revoke access instantly from the eBay developer portal',
  'Sandbox support for testing without live listings',
]
