SERVICE_MODULES : dict[str, list[str]]= {
    "backend": [
            "automana.api.services.auth.auth_service",
            "automana.api.services.auth.session_service",
            "automana.api.services.auth.cookie_utils",
            "automana.api.services.user_management.user_service",
            "automana.api.services.user_management.role_service",
            "automana.core.services.card_catalog.card_service",
            "automana.core.services.card_catalog.set_service",
            "automana.core.services.card_catalog.collection_service",
            "automana.core.services.app_integration.ebay.auth_services",
            "automana.core.services.app_integration.ebay.browsing_services",
            "automana.core.services.app_integration.ebay.selling_services",
            "automana.core.services.ops.pipeline_services",
            "automana.core.services.app_integration.scryfall.data_loader",
            "automana.core.services.app_integration.mtgjson.data_loader",
        ],

    "celery": [
            "automana.core.services.card_catalog.card_service",
            "automana.core.services.card_catalog.set_service",
            "automana.core.services.ops.pipeline_services",
            "automana.core.services.app_integration.scryfall.data_loader",
            "automana.core.services.app_integration.mtg_stock.data_loader",
            "automana.core.services.app_integration.mtg_stock.data_staging",
            "automana.core.services.analytics.reporting_services",
            "automana.core.services.app_integration.mtgjson.data_loader",
        ],
    "all" : [
            "automana.api.services.auth.auth_service",
            "automana.api.services.auth.session_service",
            "automana.api.services.auth.cookie_utils",
            "automana.api.services.user_management.user_service",
            "automana.api.services.user_management.role_service",
            "automana.core.services.card_catalog.card_service",
            "automana.core.services.card_catalog.set_service",
            "automana.core.services.card_catalog.collection_service",
            "automana.core.services.app_integration.ebay.auth_services",
            "automana.core.services.app_integration.ebay.browsing_services",
            "automana.core.services.app_integration.ebay.selling_services",
            "automana.core.services.ops.pipeline_services",
            "automana.core.services.app_integration.scryfall.data_loader",
            "automana.core.services.app_integration.mtg_stock.data_staging",
            "automana.core.services.analytics.reporting_services",
            "automana.core.services.app_integration.mtgjson.data_loader",
    ]
}