serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = 7000

auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"

transport.tls.enable = true

log.level = "info"

[[proxies]]
name = "automana"
type = "tcp"
localIP = "frontend"
localPort = 5173
remotePort = 8888

[[proxies]]
name = "postgres"
type = "tcp"
localIP = "postgres"
localPort = 5432
remotePort = 15432
