/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIdRouteImport } from './routes/listings_.$id'
import { Route as EbayShareRouteImport } from './routes/ebay/share'
import { Route as EbaySetupRouteImport } from './routes/ebay/setup'
import { Route as CardsIdRouteImport } from './routes/cards.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings_/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EbayShareRoute = EbayShareRouteImport.update({
  id: '/ebay/share',
  path: '/ebay/share',
  getParentRoute: () => rootRouteImport,
} as any)
const EbaySetupRoute = EbaySetupRouteImport.update({
  id: '/ebay/setup',
  path: '/ebay/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIdRoute = CardsIdRouteImport.update({
  id: '/cards/$id',
  path: '/cards/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/cards/$id': typeof CardsIdRoute
  '/ebay/setup': typeof EbaySetupRoute
  '/ebay/share': typeof EbayShareRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/cards/$id': typeof CardsIdRoute
  '/ebay/setup': typeof EbaySetupRoute
  '/ebay/share': typeof EbayShareRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/cards/$id': typeof CardsIdRoute
  '/ebay/setup': typeof EbaySetupRoute
  '/ebay/share': typeof EbayShareRoute
  '/listings_/$id': typeof ListingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/listings'
    | '/login'
    | '/search'
    | '/cards/$id'
    | '/ebay/setup'
    | '/ebay/share'
    | '/listings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/listings'
    | '/login'
    | '/search'
    | '/cards/$id'
    | '/ebay/setup'
    | '/ebay/share'
    | '/listings/$id'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/listings'
    | '/login'
    | '/search'
    | '/cards/$id'
    | '/ebay/setup'
    | '/ebay/share'
    | '/listings_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  ListingsRoute: typeof ListingsRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  CardsIdRoute: typeof CardsIdRoute
  EbaySetupRoute: typeof EbaySetupRoute
  EbayShareRoute: typeof EbayShareRoute
  ListingsIdRoute: typeof ListingsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings_/$id': {
      id: '/listings_/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebay/share': {
      id: '/ebay/share'
      path: '/ebay/share'
      fullPath: '/ebay/share'
      preLoaderRoute: typeof EbayShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebay/setup': {
      id: '/ebay/setup'
      path: '/ebay/setup'
      fullPath: '/ebay/setup'
      preLoaderRoute: typeof EbaySetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$id': {
      id: '/cards/$id'
      path: '/cards/$id'
      fullPath: '/cards/$id'
      preLoaderRoute: typeof CardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  ListingsRoute: ListingsRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  CardsIdRoute: CardsIdRoute,
  EbaySetupRoute: EbaySetupRoute,
  EbayShareRoute: EbayShareRoute,
  ListingsIdRoute: ListingsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
